### ISSUE TITLE
pio build && pio train && pio deploy

### ISSUE THREAD

**Issue by lgwaustralia** [andrewwuan/PredictionIO-Churn-Prediction-H2O-Sparkling-Water#1]
Having difficulty with:

[INFO] [Engine] Extracting datasource params...
[INFO] [WorkflowUtils$] No 'name' is found. Default empty String will be used.
[INFO] [Engine] Datasource params: (,DataSourceParams(3))
[INFO] [Engine] Extracting preparator params...
[INFO] [Engine] Preparator params: (,Empty)
[INFO] [Engine] Extracting serving params...
[INFO] [Engine] Serving params: (,Empty)
[INFO] [Remoting] Starting remoting
[INFO] [Remoting] Remoting started; listening on addresses :[akka.tcp://sparkDriver@10.64.110.9:55553]
[INFO] [Engine$] EngineWorkflow.train
[INFO] [Engine$] DataSource: com.sparkling.DataSource@6b1321b7
[INFO] [Engine$] Preparator: com.sparkling.Preparator@12192604
[INFO] [Engine$] AlgorithmList: List(com.sparkling.Algorithm@6b70d1fb)
[INFO] [Engine$] Data sanity check is on.
[INFO] [Engine$] com.sparkling.TrainingData does not support data sanity check. Skipping check.
[INFO] [Engine$] com.sparkling.PreparedData does not support data sanity check. Skipping check.
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/spark/sql/execution/ExistingRdd
    at com.sparkling.Algorithm.train(Algorithm.scala:28)
    at com.sparkling.Algorithm.train(Algorithm.scala:20)
    at io.prediction.controller.P2LAlgorithm.trainBase(P2LAlgorithm.scala:46)
    at io.prediction.controller.Engine$$anonfun$18.apply(Engine.scala:688)
    at io.prediction.controller.Engine$$anonfun$18.apply(Engine.scala:688)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at io.prediction.controller.Engine$.train(Engine.scala:688)
    at io.prediction.controller.Engine.train(Engine.scala:174)
    at io.prediction.workflow.CoreWorkflow$.runTrain(CoreWorkflow.scala:65)
    at io.prediction.workflow.CreateWorkflow$.main(CreateWorkflow.scala:247)
    at io.prediction.workflow.CreateWorkflow.main(CreateWorkflow.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

**Comment by andrewwuan** [comment]
@lgwaustralia This is due to that old sparkling water library doesn't support Spark version from 1.3 onward. I've just made a new release for my template `v0.1.2` and it should resolve this error.
